Update es_es.json
EdwinMindcraft/origins-architectury pull request #228
Opened 2022-08-11 14:27 UTC by albertosaurio65

2022-08-16 12:44 UTC, EdwinMindcraft requested changes
Two changes that I think were mistakes on your part, other than that, looks great.

2022-08-16 12:44 UTC, EdwinMindcraft commented on src/main/resources/assets/origins/lang/es_es.json
> +  "origins.gui.badge.recipe.crafting.shapeless": "Receta de elaboración (sin forma) proporcionada por el poder:"
You missed a comma here.
```suggestion
  "origins.gui.badge.recipe.crafting.shapeless": "Receta de elaboración (sin forma) proporcionada por el poder:",
```

2022-08-16 12:44 UTC, EdwinMindcraft commented on src/main/resources/assets/origins/lang/es_es.json
> +  "text.autoconfig.origins.title":   "origins Configuration",
Please fix the case here.
```suggestion
  "text.autoconfig.origins.title":   "Origins Configuration",
```

2022-08-16 15:54 UTC, albertosaurio65 commented
Ok, the error of the comma was that I moved it from the bottom and I forgot to put it, the capital letter was because I forgot to update that part.

I have a doubt with two things that I don't know very well where and how it is used since it has several interpretations

`  "text.autoconfig.origins.option.xOffset": "Cooldown Bar Offset X",
  "text.autoconfig.origins.option.yOffset": "Cooldown Bar Offset Y",`

2022-08-17 09:24 UTC, EdwinMindcraft commented
It appeared in the origins configuration screen when configured was used. Currently it shouldn't be used. The actual text is in Apoli.
In this case offset is a displacement vector, ie it would move the power bars by the given coordinates from their original position.

2022-08-19 13:19 UTC, merged